### ISSUE TITLE
Python tSNE failed

### ISSUE THREAD

**Issue by ludovicc** [HBPMedical/algorithm-repository#3]
Using hbpmip/python-tsne:0.3.3 with the following parameters against sample data 

PARAM_covariables=""
PARAM_grouping=""
PARAM_meta="{\"minimentalstate\":{\"description\":\"The Mini–Mental State Examination (MMSE) or Folstein test is a 30-point questionnaire that is used extensively in clinical and research settings to measure cognitive impairment. It is commonly used to screen for dementia.\",\"methodology\":\"mip-cde\",\"label\":\"MMSE Total scores\",\"minValue\":0,\"code\":\"minimentalstate\",\"maxValue\":30.0,\"type\":\"integer\"}}"
PARAM_query="SELECT \"minimentalstate\" FROM cde_features_a WHERE \"minimentalstate\" IS NOT NULL"
PARAM_variables="minimentalstate"

atsne: perplexity: 30, iters: 1000, input: /tmp/tmpoax_tmpj, output: /tmp/tmptfdm4ja6, dims: 0x0 
end atsne
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:2241: RuntimeWarning: Mean of empty slice.
  mns = a.mean(axis=axis)
/usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
Traceback (most recent call last):
  File "/tsne.py", line 278, in <module>
    main()
  File "/tsne.py", line 99, in main
    chart = generate_scatterchart(output, indep_vars, labels, perplexity, theta, iterations)
  File "/tsne.py", line 238, in generate_scatterchart
    'series': get_chart_series(data, labels)
  File "/tsne.py", line 266, in get_chart_series
    sub_data = data[mask[:, 0], :]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 757

**Comment by bldrvnlw** [comment]
Some bug in the charting logic by the looks of it, I'll look into it.

**Comment by bldrvnlw** [comment]
I've examined the testing data and the log above in detail notice a couple of things which are leading to problems. 

1) There are three possible table which could be being used here: cde_feature_a, cde_feature_b, cde_feature_c. Of these only the _b and _c table contain data in the minimentalstate column, but in cde_features_a all the values are NULL so the PARAM_query won't return anything .  

Early on there is a "mean of empty slice" error I assume is related to getting empty data from the select.

2) No covariables are specified for the tsne dimensions.

In the python-tsne/test/docker-compose.yml there is a good example of how to pass the parameters (in this case the dependent variable is name and this is also used to label output in the graph). Note the multiple covariables (4 in total) goving a 4 dimensional input.: 

      PARAM_variables: "name"
      PARAM_covariables: "sepal_length,sepal_width,petal_length,petal_width"
      PARAM_grouping: ""
      PARAM_query: "SELECT name,sepal_length,sepal_width,petal_length,petal_width FROM iris"
      PARAM_meta: "{\"name\":{\"code\":\"name\",\"type\":\"string\"},\"sepal_length\":{\"code\":\"sepal_length\",\"type\":\"real\"},\"sepal_width\":{\"code\":\"sepal_width\",\"type\":\"real\"},\"petal_length\":{\"code\":\"petal_length\",\"type\":\"real\"}, \"petal_width\":{\"code\":\"petal_width\",\"type\":\"real\"}}"
      PARAM_MODEL_dependent_is_label: "True"
      PARAM_MODEL_perplexity: 30
      PARAM_MODEL_do_zscore: "True"
      PARAM_MODEL_iterations: 1000
      PARAM_MODEL_theta: 0.5
      PARAM_MODEL_target_dimensions: 2

**Comment by bldrvnlw** [comment]
Given the comments about I think this is mainly a usage problem. Based on that I'm closing the issue but feel free to re-open it as a documentation issue (or open a new issue) and I can provide better guidance in the Readme.md file for using the python/tsne
